import type { Metadata } from 'next';
import './globals.css';
import RecoilProvider from './config/RecoilProvider';

export const metadata: Metadata = {
  title: 'supa-next',
  description: 'Generated by create next app',
};
//recoilprovider 감싸기는 body 기준입니다.
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <RecoilProvider>{children}</RecoilProvider>
      </body>
    </html>
  );
}
